{
  "errors_to_ignore": [
      ["typography.symbols.copyright", chapters\04_game_theoretic_model\01_game_theory_intro\main.tex],
      ["annotations.misc", chapters\01_introduction\main.tex],
  ],
  "files_to_ignore": [
      "\\Bin\\",
      "packages.tex",
      "Frontmatter\\acknowledgements.tex",
  ]
}
