{
  "errors_to_ignore": [
      ["typography.symbols.copyright", chapters\04_game_theoretic_model\01_game_theory_intro\main.tex],
      # Several comments in the tex files (TODOs, etc.)
      # TODO: Remove these once all the todos are done 
      ["annotations.misc", chapters\00_appendix\01_ambulance_game_library\main.tex],
      ["annotations.misc", chapters\04_game_theoretic_model\02_formulation\main.tex],
      ["annotations.misc", chapters\01_introduction\main.tex],
      ["annotations.misc", chapters\03_queueing_model\02_markov_model\01_closed_form_steady_state_probs\main.tex],
      ["annotations.misc", chapters\03_queueing_model\03_performance_measures\01_waiting_time\main.tex],
      ["annotations.misc", chapters\04_game_theoretic_model\03_methodology\main.tex],
      ["annotations.misc", chapters\05_numerical_results\01_data_collection\main.tex],
      ["annotations.misc", chapters\05_numerical_results\main.tex],
      ["annotations.misc", chapters\05_numerical_results\03_what_if\main.tex],
      ["annotations.misc", chapters\06_agent_based_extension\01_state_dependent\main.tex],
      ["annotations.misc", chapters\06_agent_based_extension\03_state_server_dependent\main.tex],
      ["annotations.misc", chapters\06_agent_based_extension\05_reinforcement_learning\main.tex],
      ["annotations.misc", chapters\07_conclusion\main.tex]
  ],
  "files_to_ignore": [
      "\\Bin\\",
      "packages.tex"
  ]
}
