name: Spelling

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install conda and activate environment
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          environment-file: ./environment.yml
          activate-environment: thesis_env

      - name: Test spellcheck
        run: inv spellcheck
