name: Spelling

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Test spellcheck
        run: inv spellcheck
