name: Ubuntu CI

on: [push, pull_request]

jobs:
  ubuntu_build:
    name: Ubuntu CI
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install conda and activate environment
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          environment-file: ./environment.yml
          activate-environment: thesis_env
      
      - name: Set up latex libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra
          sudo apt-get install -y texlive-xetex
          sudo apt-get install texlive-science
          sudo apt-get install -y latexmk
          sudo apt-get install aspell

      - name: Test PDF compiles
        run: inv compile

      - name: Test spellcheck
        run: inv spellcheck
